
package interfaceCorba;

/**
* interfaceCorba/CalculatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 27 de febrero de 2018 08:33:19 PM CST
*/

abstract public class CalculatorHelper
{
  private static String  _id = "IDL:interfaceCorba/Calculator:1.0";

  public static void insert (org.omg.CORBA.Any a, interfaceCorba.Calculator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static interfaceCorba.Calculator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (interfaceCorba.CalculatorHelper.id (), "Calculator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static interfaceCorba.Calculator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, interfaceCorba.Calculator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static interfaceCorba.Calculator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interfaceCorba.Calculator)
      return (interfaceCorba.Calculator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      interfaceCorba._CalculatorStub stub = new interfaceCorba._CalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static interfaceCorba.Calculator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interfaceCorba.Calculator)
      return (interfaceCorba.Calculator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      interfaceCorba._CalculatorStub stub = new interfaceCorba._CalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
