
package interfaceCorba;

/**
* interfaceCorba/DivisionPorCero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 27 de febrero de 2018 08:33:19 PM CST
*/

public final class DivisionPorCero extends org.omg.CORBA.UserException
{
  public float op1 = (float)0;
  public float op2 = (float)0;

  public DivisionPorCero ()
  {
    super(DivisionPorCeroHelper.id());
  } // ctor

  public DivisionPorCero (float _op1, float _op2)
  {
    super(DivisionPorCeroHelper.id());
    op1 = _op1;
    op2 = _op2;
  } // ctor


  public DivisionPorCero (String $reason, float _op1, float _op2)
  {
    super(DivisionPorCeroHelper.id() + "  " + $reason);
    op1 = _op1;
    op2 = _op2;
  } // ctor

} // class DivisionPorCero
